### PR TITLE
Attempt to fix issue WhenGryphonsFly#4 (untested)

### PR DESCRIPTION
**Pull request by H-A-M-G-E-R**

### CODE REVIEW

**Comment by simonlindholm** [comment]
The error happens because you don't have a declaration for `CountPrimarySprite`. It would be nice to detect this directly and give a proper error message rather than hope that you can guess that based on the internal error! Alternatively, falling back to `int` when a function has not been declared, since it's what C does. Kinda weary of that though, feels like it just hides errors that could help match the function.

The proposed changes in this PR don't help at all, they just change the order of pattern matching cases... I would encourage testing your fixes before PRing them.

**Comment by H-A-M-G-E-R** [comment]
i partially tested and i think it fixed the error

**Comment by H-A-M-G-E-R** [comment]
and now i don't want my solution anymore...

**Comment by simonlindholm** [comment]
Why the continuous reopen/close cycles? To be clear this PR as-is has no effect, it's effectively changing
```
if a == 1:
  do stuff 1
elif a == 2:
  do stuff 2
```
to
```
if a == 2:
  do stuff 2
elif a == 1:
  do stuff 1
```

**Comment by H-A-M-G-E-R** [comment]
because i changed my mind constantly

**Pull request closed without merging**
